project_id = "pouwjbferugzxpssgntj"

[api]
enabled = true

[functions.validate-api-keys]
verify_jwt = true

[functions.generate-images]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-video-script]
verify_jwt = true